### ISSUE TITLE
validate flist url 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#435]

**Comment by MohamedElmdary** [comment]
Tries to use make a request to fetch the flist but it seems like there is a cors issue
![image](https://user-images.githubusercontent.com/31689104/148676044-a31a5f0b-8ed7-429c-bc9c-f05ba76a47ea.png)

So I wrote a code that validate that link from `hub.grid.tf` and using `https` and ends with `.flist`
```ts
function valiteFlistUrl(url: string) {
    try {
        new URL(url);
        const [protcol, _, site, user, flist] = url.split("/")
        return protcol === "https:" && site === "hub.grid.tf" && user.length > 0 && flist.endsWith(".flist") && flist.length > ".flist".length + 1;
    }
    catch {
        return false;
    }
}
```

**Comment by xmonader** [comment]
do the request against flistUrl + `.md5` that should work

**Comment by MohamedElmdary** [comment]
Still throwing `CORS` error
![image](https://user-images.githubusercontent.com/31689104/148682542-bed18d2b-c5d7-4e2f-80ea-55983a6bda84.png)

**Comment by xmonader** [comment]
@maxux would you please be so kind and enable cors on the hub

**Comment by maxux** [comment]
Sure, I'll add that

**Comment by maxux** [comment]
Should be fixed, please check and tell me :)

**Comment by MohamedElmdary** [comment]
Still not working @maxux 
![image](https://user-images.githubusercontent.com/31689104/149345536-4311ff2a-8592-4926-bd24-d89260c53c9d.png)

**Comment by maxux** [comment]
Yes okay I see, CORS is not enabled on error (404 in this case)
Will check that.

**Comment by maxux** [comment]
Should be really fixed now.

**Comment by MohamedElmdary** [comment]
### Fixed
- Added validation before deploying

#### PR
https://github.com/threefoldtech/grid_weblets/pull/459

**Comment by dmahmouali** [comment]
Validation not working on https://play.grid.tf/#/vm

![image](https://user-images.githubusercontent.com/36021484/149782438-c03e7888-83a8-4c12-be10-532487cd7ea7.png)

**Comment by MohamedElmdary** [comment]
It's not in [play.grid.tf](play.grid.tf) yet please check on [play.dev.grid.tf](play.dev.grid.tf)

**Comment by dmahmouali** [comment]
verified on https://play.dev.grid.tf/#/vm
working fine 
![image](https://user-images.githubusercontent.com/36021484/149783557-299be4c4-ffb3-4527-9bf0-641eb2bc89e2.png)
