### ISSUE TITLE
mattermost stop working

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#641]
### Description
first, I validate it was started to work as it shows a registration form, but about 20 minutes later it stopped working as  revisiting the Mattermost deployment URL gives a gateway error,
https://mm41mmb0a2b359.gent01.dev.grid.tf/

checking the server status it seems like PostgreSQL is stucked 

### Steps to reproduce
deploying Mattermost on https://play.dev.grid.tf/

deployments details
```
{
    "version": 0,
    "contractId": 124,
    "nodeId": 2,
    "name": "mmb0a2b359",
    "created": 1649684492,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/ashraf.3bot/ashraffouda-mattermost-latest.flist",
    "publicIP": null,
    "planetary": "303:60c2:bb79:5147:cf77:141e:e2da:35b5",
    "interfaces": [
        {
            "network": "NWecb3afe0",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 1,
        "memory": 2048
    },
    "mounts": [
        {
            "name": "diskqsrvdnvtus",
            "mountPoint": "/var/lib/postgresql",
            "size": 10737418240,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "DB_PASSWORD": "o1Dlg|Fm.O",
        "SITE_URL": "https://mm41mmb0a2b359.gent01.dev.grid.tf",
        "SMTPUsername": "sameh",
        "SMTPPassword": "o1Dlg|Fm.O",
        "SMTPServer": "gmail.com",
        "SMTPPort": "587",
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9MI7fh4xEOOEKL7PvLvXmSeRWesToj6E26bbDASvlZnyzlSKFLuYRpnVjkr8JcuWKZP6RQn8+2aRs6Owyx7Tx+9kmEh7WI5fol0JNDn1D0gjp4XtGnqnON7d0d5oFI+EjQQwgCZwvg0PnV/2DYoH4GJ6KPCclPz4a6eXrblCLA2CHTzghDgyj2x5B4vB3rtoI/GAYYNqxB7REngOG6hct8vdtSndeY1sxuRoBnophf7MPHklRQ6EG2GxQVzAOsBgGHWSJPsXQkxbs8am0C9uEDL+BJuSyFbc/fSRKptU1UmS18kdEjRgGNoQD7D+Maxh1EbmudYqKW92TVgdxXWTQv1b1+3dG5+9g+hIWkbKZCBcfMe4nA5H7qerLvoFWLl6dKhayt1xx5mv8XhXCpEC22/XHxhRBHBaWwSSI+QPOCvs4cdrn4sQU+EXsy7+T7FIXPeWiC2jhFd6j8WIHAv6/rRPsiwV1dobzZOrCxTOnrqPB+756t7ANxuktsVlAZaM= sameh@sameh-inspiron-3576"
    },
    "entrypoint": "/sbin/zinit init",
    "metadata": "",
    "description": "",
    "corex": false
}

```
### Logs/Alerts
```
root@mmb0a2b359:~# zinit list
---
ufw: Success
sshd: Running
sshkey: Success
mattermost: Blocked
postgresql: Spawned
```
```
root@mmb0a2b359:~# zinit log

[+] postgresql/test: /var/run/postgresql:5432 - no response
[+] postgresql/test: /var/run/postgresql:5432 - no response
[+] postgresql:  * Starting PostgreSQL 12 database server
[+] postgresql:  * Error: /var/lib/postgresql/12/main is not accessible or does not exist
[+] postgresql:    ...fail!
[+] postgresql:  * Stopping PostgreSQL 12 database server
[+] postgresql:  * Error: /var/lib/postgresql/12/main is not accessible or does not exist
[+] postgresql:    ...fail!
[+] postgresql: postgres: could not access directory "/var/lib/postgresql/12/main": No such file or directory
[+] postgresql: Run initdb or pg_basebackup to initialize a PostgreSQL data directory.
[+] postgresql/test: /var/run/postgresql:5432 - no response
[+] postgresql/test: /var/run/postgresql:5432 - no response
[+] postgresql:  * Starting PostgreSQL 12 database server
[+] postgresql:  * Error: /var/lib/postgresql/12/main is not accessible or does not exist
[+] postgresql:    ...fail!
[+] postgresql:  * Stopping PostgreSQL 12 database server
[+] postgresql:  * Error: /var/lib/postgresql/12/main is not accessible or does not exist
[+] postgresql:    ...fail!
[+] postgresql: postgres: could not access directory "/var/lib/postgresql/12/main": No such file or directory
[+] postgresql: Run initdb or pg_basebackup to initialize a PostgreSQL data directory.
```

**Comment by mohamedamer453** [comment]
Tested it again on testnet v1.4.1-rc2 and on devnet and the issue is still not fixed and mattermost deployments are not working. And again it's related to the same Postgres error.
```
[+] postgresql:    ...fail!
[+] postgresql:  * Stopping PostgreSQL 12 database server
[+] postgresql:  * Error: /var/lib/postgresql/12/main is not accessible or does not exist
```
Also i will close other issues related to this issue and add them here for reference and more logs/details about the issue.  
here are the other related issues
#615 
#653

**Comment by ashraffouda** [comment]
the issue because postgres dir is mount which is wrong because it will be empty at first run which will prevent mattermost from running 
fixed here https://github.com/threefoldtech/grid_weblets/pull/675

**Comment by mohamedamer453** [comment]
I tried deploying again on devnet but now i'm facing another issue and still receiving a `Bad Gateway`

```
[+] mattermost: psql:/tmp/init_postgres.sql:5: ERROR:  extension "pg_trgm" already exists
[+] postgresql: 2022-05-09 10:14:37.212 UTC [610] postgres@mattermost ERROR:  extension "unaccent" already exists
[+] postgresql: 2022-05-09 10:14:37.212 UTC [610] postgres@mattermost STATEMENT:  CREATE EXTENSION unaccent;
[+] mattermost: psql:/tmp/init_postgres.sql:6: ERROR:  extension "unaccent" already exists
[+] mattermost: Using existing config file /mattermost/config/config.json
[+] mattermost: OK
[+] mattermost: Starting mattermost
[+] mattermost: mattermost
[+] mattermost: {"timestamp":"2022-05-09 10:14:39.321 Z","level":"error","msg":"Failed to ping DB","caller":"sqlstore/store.go:271","error":"parse \"postgres://mattermost:qXV2s_cFm%@localhost:5432/mattermost?sslmode=disable&connect_timeout=10\": invalid URL escape \"%\"","retrying in seconds":10}

``` 

Full logs can be found here:  [Mattermost_logs_new.txt](https://github.com/threefoldtech/grid_weblets/files/8650768/Mattermost_logs_new.txt)
